---
driver:
  name: digitalocean

provisioner:
  name: chef_zero

platforms:
  - name: centos-7-2-x64
    driver_config:
      size: 2gb
#  - name: ubuntu-16-04-x64
#    driver_config:
#      size: 2gb
#  - name: ubuntu-14-04-x64
#    driver_config:
#      size: 1gb
suites:
  - name: default
    server_name: cookbook_test
    vm_hostname: "#{File.basename(Dir.getwd)}_test_kitchen"
#    encrypted_data_bag_secret_key_path: test/integration/fixtures/encrypted_data_bag_secret
#    data_bags_path: test/integration/fixtures/data_bags
    run_list:
      - recipe[minecraft-server::default]
    attributes:

transport:
  ssh_key: C:/Users/Mac/.ssh/macgenius